// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_programacion.Data;

#nullable disable

namespace proyecto_programacion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918233755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("proyecto_programacion.Models.Activo", b =>
                {
                    b.Property<int>("activo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Categoriacateg_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ubicacionubic_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categ_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cod_act")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha_com")
                        .HasColumnType("TEXT");

                    b.Property<string>("modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom_act")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("num_serie")
                        .HasColumnType("TEXT");

                    b.Property<string>("proveedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("ubic_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("activo_id");

                    b.HasIndex("Categoriacateg_id");

                    b.HasIndex("Ubicacionubic_id");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("proyecto_programacion.Models.Categoria", b =>
                {
                    b.Property<int>("categ_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom_categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categ_id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("proyecto_programacion.Models.Ubicacion", b =>
                {
                    b.Property<int>("ubic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom_ubica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ubic_id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("proyecto_programacion.Models.Activo", b =>
                {
                    b.HasOne("proyecto_programacion.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Categoriacateg_id");

                    b.HasOne("proyecto_programacion.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("Ubicacionubic_id");

                    b.Navigation("Categoria");

                    b.Navigation("Ubicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
